version: '3'

services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./var/log:/var/log/nginx
        depends_on:
            - php-fpm
        ports:
            - "8888:80"
        networks:
            - dev-symfony

    php-fpm:
        container_name: php
        build:
            context: ./docker/php-fpm
        environment:
            - APP_ENV=${APP_ENV}
        volumes:
            - ./:/var/www
            - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php-fpm/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - dev-symfony
        depends_on:
            - database

    maildev:
        image: maildev/maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - "8083:80"
        restart: always
        networks:
            - dev-symfony

    node:
        container_name: node
        image: "node:lts-alpine"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=developement
        volumes:
            - ./:/home/node/app
        ports:
            - "4000:3000"
        command: >
            sh -c "yarn install
            && yarn dev"
        networks:
            - dev-symfony

    database:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: testdb
        ports:
            - "15433:5432"
        networks:
            - dev-symfony
        volumes:
            - /var/lib/postgresql/data

networks:
    dev-symfony:

volumes:
    db-data-symfony:
