controllers:
    resource: ../src/Module/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

authentication_token:
    path: /api/authentication/token
    methods: ['POST']

reset_password:
    path: /user/reset-password
    methods: ['POST']